name = "BRAF Halloween Extras"
author = "BRAF Team & Ludwig"
prefix = "halloween"
mainprefix = "braf"

[properties]
author = "BRAF Team & Ludwig"
url = "https://brafmod.com.br"
requiredVersion = 0.1

[version]
path = "addons/main/script_version.hpp" # Default
major = 1                               # Overrides path when set
minor = 0
patch = 0
build = 0                               # Optional
git_hash = 8                            # Default: 8
