name: Publish

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v3
            - name: Lint (sqflint)
              uses: arma-actions/sqflint@master
              continue-on-error: true

    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v3
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt release
            - name: Extract Zipped Mod
              run: unzip releases/braf_halloween-latest.zip -d releases
            - uses: arma-actions/workshop-upload@v1
              with:
                  appId: '107410'
                  itemId: ${{ secrets.STEAM_WORKSHOP_ITEM_ID }}
                  contentPath: releases/@braf_halloween
                  changelog: 'Update'
              env:
                  STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
                  STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            - name: Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  DISCORD_USERNAME: Saci
                  DISCORD_AVATAR: https://scontent.fpoa33-1.fna.fbcdn.net/v/t1.6435-9/123089286_2720897204844263_4695033759855672932_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=810d5f&_nc_eui2=AeHYW_2fgJH67ADthIzboTmE_dndmKxNqvb92d2YrE2q9oc1UC5FYvsZ-cUbwpH19bbxxRLaBL159Gtrl1Ug8_dM&_nc_ohc=UeyYATHroS8AX_kcFzz&_nc_ht=scontent.fpoa33-1.fna&oh=00_AfBXqiIg5a0tqgq0jvWVk_tuAlejutmjUk8KgHP-EBLuGA&oe=655A728E
                  DISCORD_EMBED: '[{"id":652627557,"title":"${{github.repository_owner}}-${{github.repository}}","description":"Commit${{github.sha}}","color":16515072,"fields":[],"author":{"name":"${{github.actor}}","url":"https://github.com/${{github.actor}}","icon_url":"https://avatars.githubusercontent.com/${{github.actor}}"}}]'
              uses: Ilshidur/action-discord@master
              with:
                  args: '{{ EVENT_PAYLOAD.repository.full_name }} acabou de ser atualizado e publicado na Workshop por ${{github.actor}}'
