name: Publish

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v3
            - name: Lint (sqflint)
              uses: arma-actions/sqflint@master
              continue-on-error: true

    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v3
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: hemtt release
            - name: Extract Zipped Mod
              run: unzip releases/braf_halloween-latest.zip -d releases
            - uses: arma-actions/workshop-upload@v1
              with:
                  appId: '107410'
                  itemId: ${{ secrets.STEAM_WORKSHOP_ITEM_ID }}
                  contentPath: releases/@braf_halloween
                  changelog: 'Update'
              env:
                  STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
                  STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            - name: Discord notification
              uses: tsickert/discord-webhook@v5.3.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                  embed-title: ${{ github.repository_owner }} - ${{ github.repository  }}
                  embed-url: false
                  embed-description: 'Commit ${{ github.sha }} - ${{ github.event.head_commit.message }}\n autorizado e mod publicado no Steam Workshop!'
                  embed-timestamp: false
                  embed-color: 16515072
                  embed-footer-text: false
                  embed-footer-icon-url: false
                  embed-image-url: false
                  embed-thumbnail-url: false
                  embed-author-name: ${{ github.actor }}
                  embed-author-url: https://github.com/${{ github.actor }}
                  embed-author-icon-url: https://avatars.githubusercontent.com/${{ github.actor }}
